/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apagar;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    int x, y;

    public Vista() {
        initComponents();
        setSize(350, 550);
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cerrar = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        lbl_apagado = new javax.swing.JLabel();
        lbl_linea = new javax.swing.JLabel();
        lbl_automatico = new javax.swing.JLabel();
        lbl_hoas1 = new javax.swing.JLabel();
        lbl_hoas = new javax.swing.JLabel();
        txt_minutos = new javax.swing.JTextField();
        txt_horas = new javax.swing.JTextField();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 500));
        setSize(new java.awt.Dimension(350, 550));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setFocusable(false);
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar2.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar);
        btn_cerrar.setBounds(270, 30, 40, 22);

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(lbl_logo);
        lbl_logo.setBounds(30, 70, 110, 110);

        lbl_apagado.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_apagado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_apagado.setText("Apagado");
        getContentPane().add(lbl_apagado);
        lbl_apagado.setBounds(160, 90, 130, 40);

        lbl_linea.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_linea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_linea.setText("_________");
        getContentPane().add(lbl_linea);
        lbl_linea.setBounds(146, 100, 160, 40);

        lbl_automatico.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_automatico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_automatico.setText("automatico");
        getContentPane().add(lbl_automatico);
        lbl_automatico.setBounds(150, 130, 150, 40);

        lbl_hoas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_hoas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hoas1.setText("Minutos");
        getContentPane().add(lbl_hoas1);
        lbl_hoas1.setBounds(205, 360, 70, 22);

        lbl_hoas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_hoas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hoas.setText("Horas");
        getContentPane().add(lbl_hoas);
        lbl_hoas.setBounds(65, 360, 50, 22);

        txt_minutos.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        txt_minutos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_minutos.setText("00");
        txt_minutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_minutosKeyTyped(evt);
            }
        });
        getContentPane().add(txt_minutos);
        txt_minutos.setBounds(180, 240, 120, 110);

        txt_horas.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        txt_horas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_horas.setText("00");
        txt_horas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_horasKeyTyped(evt);
            }
        });
        getContentPane().add(txt_horas);
        txt_horas.setBounds(30, 240, 120, 110);

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(lbl_fondo);
        lbl_fondo.setBounds(0, 0, 350, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        x = evt.getX();
        y = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);


    }//GEN-LAST:event_formMouseDragged

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txt_horasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_horasKeyTyped

        char c = evt.getKeyChar();

        if (txt_horas.getText().length() >= 2) {
            evt.consume();
        } else {

            if (!Character.isDigit(c)) {
                evt.consume();
            }

        }


    }//GEN-LAST:event_txt_horasKeyTyped

    private void txt_minutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_minutosKeyTyped

        char c = evt.getKeyChar();

        if (txt_minutos.getText().length() >= 2) {
            evt.consume();
        } else {

            if (!Character.isDigit(c)) {
                evt.consume();
            }

        }

    }//GEN-LAST:event_txt_minutosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel lbl_apagado;
    private javax.swing.JLabel lbl_automatico;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_hoas;
    private javax.swing.JLabel lbl_hoas1;
    private javax.swing.JLabel lbl_linea;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JTextField txt_horas;
    private javax.swing.JTextField txt_minutos;
    // End of variables declaration//GEN-END:variables
}
